#!/bin/sh

test -x /sbin/iptables || exit 0

case "$1" in
        start)
                echo -n "Enabling iptables firewall rules: "
		/etc/iptables/addrules.sh
		echo "done"
                ;;
        stop)
                echo -n "Flushing all iptables firewall rules: "
		/etc/iptables/flushrules.sh
		echo "done"
                ;;
        restart)
                $0 stop
                sleep 2
                $0 start
                ;;
        *)
                echo "Usage: /etc/init.d/iptables {start|stop|restart}"
                exit 1
esac

exit 0
